# Generated by Django 5.2 on 2025-06-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="copies_available",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="book",
            name="is_borrowable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="book",
            name="is_buyable",
            field=models.BooleanField(default=True),
        ),
    ]
