# Generated by Django 5.2 on 2025-05-02 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_reviews_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='User',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='User',
            new_name='user',
        ),
    ]
